context:
  version: "2.2.0"

package:
  name: harper
  version: ${{ version }}

source:
  url: https://github.com/elijah-potter/harper/archive/v${{ version }}.tar.gz
  sha256: 25f521bac7ee0aa260948d2b0de356cc55d731ad38f54a8f433f380e79bbeae4

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - harper-cli --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The Grammar Checker for Developers
  homepage: https://github.com/elijah-potter/harper
  repository: https://github.com/elijah-potter/harper

extra:
  recipe-maintainers:
    - danielnachun
