context:
  version: "2.2.1"

package:
  name: harper
  version: ${{ version }}

source:
  url: https://github.com/elijah-potter/harper/archive/v${{ version }}.tar.gz
  sha256: 44b0a9df72bac70905ef2e6a472e405bbf0233b61c00a5fce515fffc834ebc0e

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - harper-cli --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The Grammar Checker for Developers
  homepage: https://github.com/elijah-potter/harper
  repository: https://github.com/elijah-potter/harper

extra:
  recipe-maintainers:
    - danielnachun
