context:
  version: "2.3.1"

package:
  name: harper
  version: ${{ version }}

source:
  url: https://github.com/elijah-potter/harper/archive/v${{ version }}.tar.gz
  sha256: 34803150820aca1e254736999ffb09820a9332e0135cb895a7a1b1210c65ffe2

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - harper-cli --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The Grammar Checker for Developers
  homepage: https://github.com/elijah-potter/harper
  repository: https://github.com/elijah-potter/harper

extra:
  recipe-maintainers:
    - danielnachun
